# Generated by Django 4.1.7 on 2023-04-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('images', models.ImageField(null=True, upload_to='Media')),
                ('niveau', models.CharField(max_length=50)),
                ('nbr_px', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='Jattends vos questions...')),
                ('nbr_points', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageQuizz.quizz')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.CharField(max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageQuizz.question')),
            ],
        ),
    ]
