# Generated by Django 4.1.7 on 2023-04-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=90)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizz',
            name='categorie',
        ),
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manageQuizz.quizz'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[('Science', 'sci'), ('Litterature', 'ltt'), ('Informatique', 'info'), ('Mythologie', 'mtl')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageQuizz.categorie'),
        ),
    ]
