<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuizz', '0002_categorie_remove_quizz_categorie_question_quizz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.CharField(choices=[('Science', 'Science'), ('Litterature', 'Litterature'), ('Informatique', 'Informatique'), ('Mythologie', 'Mythologie')], max_length=90),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[('Expert', 'Expert+'), ('Difficile', 'Difficile'), ('Normal', 'Normal'), ('Facile', 'Facile')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
=======
# Generated by Django 4.1.7 on 2023-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageQuizz', '0002_categorie_remove_quizz_categorie_question_quizz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categorie',
            field=models.CharField(choices=[('Science', 'Science'), ('Litterature', 'Litterature'), ('Informatique', 'Informatique'), ('Mythologie', 'Mythologie')], max_length=90),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='niveau',
            field=models.CharField(choices=[('Expert', 'Expert+'), ('Difficile', 'Difficile'), ('Normal', 'Normal'), ('Facile', 'Facile')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
>>>>>>> debdd121a0ae1b44b1acc4613d7d9b75efb8eeb7
