# Generated by Django 4.1.7 on 2023-03-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=50)),
                ('nbr_px', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('nbr_points', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manageQuizz.quizz')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageQuizz.proposition')),
            ],
        ),
    ]
